name: Backend CI/CD

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  pull_request:
    branches:
      - main  # Runs on PRs to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Tests (Optional)
        run: |
          cd backend
          pytest || echo "No tests found, skipping..."

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          cd backend
          docker build -t your-dockerhub-username/backend:latest .
          docker push your-dockerhub-username/backend:latest

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull your-dockerhub-username/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 8000:8000 -p 8001:8001 your-dockerhub-username/backend:latest
